version: 2
updates:

- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: quarterly

- package-ecosystem: "docker-compose"
  directory: "/"
  schedule:
    interval: quarterly
